# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{msg-flukso-localinterface}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Dalheimer"]
  s.date = %q{2010-07-08}
  s.default_executable = %q{msg-flukso-discover}
  s.description = %q{The mySmartGrid project provides means to manage your household energy consumption. This gem provides the runtime environment for the Chumby: it queries the mySmartGrid webservice and forwards that information to a Flash application running on the Chumby.}
  s.email = %q{md@gonium.net}
  s.executables = ["msg-flukso-discover", "msg-flukso-currentwatts"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "VERSION",
     "bin/msg-flukso-currentwatts",
     "bin/msg-flukso-discover",
     "lib/msg-flukso-localinterface.rb",
     "lib/msg-flukso-localinterface/discover.rb",
     "lib/msg-flukso-localinterface/query.rb"
  ]
  s.homepage = %q{http://github.com/gonium/msg-flukso-localinterface}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Displays various information from the mySmartGrid project on your Chumby}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 1.2.3"])
    else
      s.add_dependency(%q<json>, [">= 1.2.3"])
    end
  else
    s.add_dependency(%q<json>, [">= 1.2.3"])
  end
end

